import csv
import re
import string   

def turk_tokenization(text):
	text = re.sub('([.,!?()])', r' \1 ', text)
	text = re.sub('\s{2,}', ' ', text)
	return text.split()


if __name__ == '__main__':
	COLUMNS = ['review1','review2']
	reviews = ["This hotel is lovely. We checked in straight away, our room was very spacious and very clean. There was a TV, fridge, hairdryer and a nice view over a lake from the window. The room was cleaned with fresh towels every day.The Universal Parks are just a few minutes walk away from the hotel or you can catch a boat. One of the best features of staying here is having your room key as your fast pass to skip the very large lines to get on the rides. Also the pool is fantastic and huge so you never feel crowded, all very relaxing.All the staff were very friendly and they were all only too pleased to help you if you needed something.We had a fantastic holiday and are counting the days til we can go back and do it all over again.",
				"Got a discount rate thanks to my annual pass, but probably would have been pleased paying the rack rate as well. The rooms are on the small side, but it's not like we spent much time there. Beautiful decor, friendly staff, and an amazing pool that could hold over a hundred people and still be roomy. Was concerned about dogs being allowed, but rarely saw them and certainly didn't notice any on my floor. The proximity to Universal and express pass on the rides are invaluable -- water taxi is nice but we used the garden path most times because it took less time. Avoid eating at the hotel, though -- believe it or not, the parks and City Walk are less expensive. Had dinner at a City Walk place called the Latin Quarter that was great!",
				"I had a great stay at this hotel, one myself and my family enjoyed very much. There was everything you wnated in the hotel. The rooms were nice and not old and the food was fantastic. I especially recomend Tchoup chop, the restaurent run by the chef Emril and had two fantastic meals. Perhaps breakfast was overpriced but you could easily get something in the parks. However what was brillant was when you were at a universal Park all you had to do was show them you room key and you went to the front of all the rides. also visited the other hotels and i felt that the royal Pacific matched them if not was better. Definatly recommend!",
				"Stayed here Jan 06. Four day mini vacation and what a dissapointment. Very small rooms, not very knowledgable front desk people. Not much to eat after 10 pm but the real problem was cleanliness of bathroom. When we checked in the bathroom was terrible. Asked 3 times for room to be recleaned and was assured room would be taken care of. Even had houskeeping Mng agree it was unacceptable and even after 3 times it still never got done until I called manager. They would not compensate nor did we ask but i dont think 3/4 of vacation should be spent asking them to pleeeeeze clean the room. As far as express pass that was awesome and parks were great. i just wish we had a better room to come home to. very Dissapointed wit Royal pacific",
				"We stayed at this hotel during a one week stay in Orlando. The hotel public areas, including the pool area were clean and attractive but we found the hotel room very average. The walls were thin and we heard everyone who passed by our room, some of whom were very loud any rowdy. The bedding was worn and the housekeeping staff was not very accomplished at making the beds and setting out the towels. On the positive side, the quick breakfast area near the lobby was very convenient, and reasonably priced and had great bagels and pastries. The hotel's close proximity to the Universal theme parks and the Express Pass made this stay worthwhile. With the Express Pass we were able to bypass hours of lines to be access the most popular rides over and over. ",
				"I stayed with my mom in the middle of June. We had a wonderful time staying by the pool, and using the express passes at Universal Studios. But the day we got to our hotel, we had to wait like 5 hours to get our room! We had to just sit around, we couldn't do anything! The lady at the desk forgot to give us our lays and drinks, too. Then, we got to our room and our bedspreads had stains, as well as the floor (most likely from a dog). The rooms themselves were kind of plain, nothing special. We did have a great view of the pool, though. The last day we were there we went down to breakfast, and the food wasn't all that great. Maybe next time we'll try another hotel!",
				"Check-in was a breeze. The Express Admissions to both Universal Studios and Islands Of Adventure (which we could use numerous times) saved us quite a bit of wait time in the lines which got longer as the day progressed. The hotel's restaurants were a bit too pricey for our budget, so we ate either at the amusement parks or elsewhere. We used the water taxi from the resort to the hotel and never had to wait more than 15 minutes for one. The staff at the Royal Pacific Resort were very friendly and accomodating. They even sent my daughter up a surprise gift basket for her birthday. The rooms were adequate in size and quite comfortable.",
				"Stayed at the RP in July 2006 with a group of 28. Ages range from 3 to 45. Check in was a breeze. Arrived early in the morning. We were given our park passes and recieved a call from the front desk once our room was ready. The first day or two we found ourselves waiting for the water taxi to get to the parks. We then began to walk along the path to get to the park. The walk was a nice walk along the waterway. The hotel has a great pool area. Nice to relax in the pool after a long day of walking. We ate on property and found that the food was worth the money. Hotel rooms were nice, the bell service was excellent. Had a great vacation and we would return to this hotel. Finally, by staying on a Universal Property you get to bypass the regular lines. This was worth the extra money by itself.",
				"My 2 daughters and I just returned from a quick 2 night stay at the Royal Pacific Resort and loved it. The decor of the hotel was a beautiful Balinese, the service was great (did room-service, took the boat to Islands of Adventure, etc) and loved the on site Emeril's restaurant. This hotel is great for a trip to Universal or Islands of Adventure because of the ease of getting to the parks (a 5 minute boat ride) and the use of the Express Pass with your room key. I compare all hotels to the Ritz or Four Seasons and this one isn't far off - the rooms are smallish but comfortable and nicely decorated/updated and the common areas were very well done and well-maintained. The crowds here all seemed relatively up-scale.",
				"Oh my goodness! This is the most beautiful hotel I have ever stayed in. First off the staff was happy to help with anything I needed. (Including getting to my room at 3:00 in the morning when I forgot my room key). The pool was among the best. After long days in the hot sun coming back to the hotel and just relaxing by the pool was a major +. Emeralds restaraunt was delicious even though the almost $600 bill was not as delightful. The breakfast bar in the dining area was beautiful. My kids loved the room service and we are planing on surprising them with another week stay in July!!! Recommended to any classy family or anyone who just enjoys being treated like Kings and Queens! Also the Luau was wonderful and hilarious at the same time",
				"Very expensive, but worth it to have front of line pass. Pool was freezing (in June). Forgot to give me my welcome gift with Lowes First card. Asked for bathrobes (free with stay on club level), never came. $12.00 per day to self park a mile away. But hotel was beautiful, lots of great treats in club lounge. Boat ride to parks was intermittent, some came quick (like one every two minutes), some came once every half hour. You could not count on them, but much better than walking. Gift shops were small, but nice. I would stay again only because of the front of the line pass, without that it would not have been worth it.",
				"Very nice. No surprise for the price and being part of Universal. The best part was your hotel key worked as a fast pass at the universal theme parks with few limits. Walking distance to Universal, or cantake the ferry. Nice large pool, swim area. Most on site restaurants were pricey, and the kids didn'tlike the selection. We ate mostly at the theme park or city walk restaurants. Staff was professional, but very commerical. Again, that was expected for a large resort. This trip was part vacation and business since I had a convention at the resort.",
				"My family loved the Royal Pacific Resort. We went there mainly to take advantate of the front of the line priviledges at the Universal parks (which was absolutely invaluable since we were there at high season). But, once there, we fell in love with the beautiful hotel buildings and grounds. There is a very convenient free water taxi service linking the hotel to the Universal parks (about a 10 minute ride) which we used to take a mid-day break from the theme park to cool down and refresh in the hotel pool. All in all, we highly recommend this hotel.",
				"A great impression at first but soon to discover it's an overpriced resort with less than \"pampering\" service for the price you'll pay. They seemed more concerned with getting every dollar out of their guests than providing a quality stay at their hotel. $12 a day extra just to park your car? Please! Everything is overpriced. You can find a much nicer hotel in the area. And it was not so convenient staying so close to the park with waiting 20-30 minutes for the boat to take us from the parks back to the hotel every night. They wouldn't even let a group of young girls on the boat at 11 PM because they didn't have their parents room key to show the boat operator. The girls had to walk back to the hotel in the dark at 11PM! What kind of resort does this??? I'll never go back.",
				"I had earned a free Universal vacation through my credit card and my husband and I took my parents. We stayed in basic room at Royal Pacific and were very impressed. I do like the conveniences of cheaper hotel rooms (microwave, fridge) but other than that, the room was great. Beds were super comfy, small but nice bathrooms. Prices were high at on-site restaurants but I expected that. What I did not expect was having to pay for parking (was surprised about that since Disney don't charge). I have also stayed at Old Key West and Saratoga at Disney and out of the three, I would pick Royal Pacific. Plus, the advantages of just staying on site are great",
				"What a disappointment, went to relax with my 2 college girls. We all drove seperately as we live in different states. They charge for parking every day, they charge to use the workout room and if you use it more than once a day, you pay again, per person. They charge for internet service, please, it is wireless. They charge to print one sheet out for you. They charge for breakfast and it is not cheap. Every where you step in this hotel, there is a charge. After paying $250/night for the room, I think atleast internet and the workout room should be included. There is no real choice restaurants to go to unless you stay right in the hotel. All restaurants there are great. I will definitely not go again, I can use my money much more wisely",
				"I will make this short and sweet. The customer service we received from the hotel rivals any Ritz or St. Regis (our favorites). We stayed in the park so that it would be convenient for our teenage daughters and we were pleasantly surprised. Please don't be confused.....the beds weren't great, lots of children everywhere (to be expected) small rooms and there were dogs everywhere (allergic to pet dander) but, any request we made was taken care of immediately and cordially. We were never told \"no\". Our girls enjoyed the pool and easy access to the parks and that is the reason we went to Orlando in the first place.",
				"When we arrived the agent told me that I could not park in front of the hotel even to check in. After I registered, I walked back to the car and then we walked back to the hotel carrying our luggage. The room temperature was set at 72 degrees and you can't adjust it. The sink was cracked in the center, the freestanding lamp did not work and there was large brown hairs on the shower wall. There's a boat shuttle that takes you to CityWalk usually the wait is 20 minutes. Your room key is an Express Pass in Universal Studios which you can't beat. I will try another hotel at Universal next time.",
				"We stayed here for 7 days, our kids loved the pool espically the frozen grapes mid afternoon to cool you down. The staff were friendly and chatty made the hotel a pleasure to stay at, the staff at the pool side grill were great could not do enough for you! The use of our room card for universal express pass was invaluable. The hotel interior far exceeded my expectations, and spotlessly clean, the turn down service at night was a lovely touch they always put our childrens teddy bears ready and waiting for them in bed! Wouldn't hesitate to stay again.",
				"We went on our anniversary. Positives are soft sheets, dog friendly (dog park and dog welcome package), very nice staff, water taxi to CitiWalk and Universal Parks, room key doubles as Express Pass for rides in park, and the food in the hotel restaurants is better than your average park food. The sushi at the Orchid Court Lounge was excellent and highly recommended. The only negative would matter to dog people - it was great having a dog park so close to our room, but it was not completely fenced in and near busy streets, so it was not possible to let them off their leash to run around. Overall, the only way to go to Universal Orlando because the water taxi and Express Pass is well worth the extra cost for the hotel.",
				]

	# For debug purpose, compare consecutive reviews

	with open('input.csv', 'w') as csv_file:
		writer = csv.DictWriter(csv_file, fieldnames=COLUMNS)
		writer.writeheader()

		for id, i in enumerate(range(0, len(reviews), 2)):
			pair = {'review1': '>>'.join(turk_tokenization(reviews[i])),
					'review2': '>>'.join(turk_tokenization(reviews[i+1])),
					}
			writer.writerow(pair);

	csv_file.close()